version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 64865542512000
      POSTGRES_DB: memogate_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: memogate_backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}  # Берет значение из .env
      JWT_SECRET: ${JWT_SECRET}      # Берет значение из .env
    ports:
      - "5173:5173"

volumes:
  postgres_data:
